export const GITHUB_OWNER = 'Bennu';

export interface TemplateItem {
  id: string;
  name: string;
  repo: string;
  branch: string;
  desc: string;
  badge: string;
  logo: string;
  logoColor: string;
  comingSoon?: boolean;
}

export const BACKEND_TEMPLATES: TemplateItem[] = [
  {
    id: 'template_quarkus-mybatis',
    name: 'Quarkus + MyBatis',
    repo: 'template_quarkus-mybatis',
    branch: 'main',
    desc: 'Framework Java nativo con persistencia MyBatis',
    badge: 'Java',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/quarkus.svg',
    logoColor: '#4695EB',
  },
  {
    id: 'template_ms-golang',
    name: 'Go Microservices',
    repo: 'template_ms-golang',
    branch: 'main',
    desc: 'Arquitectura de microservicios en Go',
    badge: 'Go',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/go.svg',
    logoColor: '#00ADD8',
  },
  {
    id: 'java-mvc',
    name: 'Java MVC',
    repo: 'template_java-mvc',
    branch: 'main',
    desc: 'Aplicación empresarial con patrón MVC',
    badge: 'Java',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/java.svg',
    logoColor: '#ED8B00',
  },
  {
    id: 'springboot-quartz',
    name: 'Spring Boot + Quartz',
    repo: 'template_springboot-quartz',
    branch: 'main',
    desc: 'Planificador de tareas con Spring Boot',
    badge: 'Java',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/spring.svg',
    logoColor: '#6DB33F',
  },
  {
    id: 'springboot-mybatis',
    name: 'Spring Boot + MyBatis',
    repo: 'template_springboot-mybatis',
    branch: 'main',
    desc: 'ORM flexible con Spring Boot',
    badge: 'Java',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/spring.svg',
    logoColor: '#6DB33F',
  },
  {
    id: 'java-multi-module',
    name: 'Java Multi-Módulo',
    repo: 'template_java-multi-module',
    branch: 'main',
    desc: 'Proyecto modular escalable en Java',
    badge: 'Java',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/java.svg',
    logoColor: '#F80000',
    comingSoon: true,
  },
  {
    id: 'quarkus-cqrs-query',
    name: 'Quarkus CQRS (Query)',
    repo: 'template_quarkus-cqrs-query',
    branch: 'main',
    desc: 'Patrón CQRS lado lectura en Java',
    badge: 'Quarkus',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/quarkus.svg',
    logoColor: '#4695EB',
    comingSoon: true,
  },
  {
    id: 'quarkus-cqrs-commander',
    name: 'Quarkus CQRS (Command)',
    repo: 'template_quarkus-cqrs-commander',
    branch: 'main',
    desc: 'Patrón CQRS lado escritura en Java',
    badge: 'Quarkus',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/quarkus.svg',
    logoColor: '#4695EB',
    comingSoon: true,
  },
];

export const FRONTEND_TEMPLATES: TemplateItem[] = [
  {
    id: 'react',
    name: 'Next.js',
    repo: 'template_react',
    branch: 'feat/template-v1',
    desc: 'Librería UI moderna con Hooks',
    badge: 'Next.js',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/nextdotjs.svg',
    logoColor: '#61DAFB',
  },
  {
    id: 'angular',
    name: 'Angular',
    repo: 'template_angular',
    branch: 'main',
    desc: 'Framework completo con TypeScript',
    badge: 'Angular',
    logo: 'https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/angular.svg',
    logoColor: '#DD0031',
  },
];

export const MOCK_TREES: Record<string, string[]> = {
  'quarkus-mybatis': [
    'src/main/java/com/example/',
    'src/main/java/com/example/Application.java',
    'src/main/java/com/example/controller/',
    'src/main/java/com/example/service/',
    'src/main/java/com/example/mapper/',
    'src/main/resources/application.yml',
    'src/test/java/',
    'pom.xml',
    'Dockerfile',
  ],
  'ms-golang': [
    'cmd/',
    'cmd/api/main.go',
    'internal/',
    'internal/handler/',
    'internal/service/',
    'internal/storage/',
    'pkg/',
    'deployments/',
    'deployments/docker-compose.yml',
    'go.mod',
    'go.sum',
    'Dockerfile',
    '.dockerignore',
  ],
  'java-mvc': [
    'src/main/java/',
    'src/main/java/controller/',
    'src/main/java/service/',
    'src/main/java/model/',
    'src/main/resources/',
    'src/main/webapp/',
    'src/test/',
    'pom.xml',
    'README.md',
  ],
  'springboot-quartz': [
    'src/main/java/com/example/',
    'src/main/java/com/example/config/',
    'src/main/java/com/example/job/',
    'src/main/java/com/example/service/',
    'src/main/resources/application.yml',
    'src/test/java/',
    'pom.xml',
    'Dockerfile',
  ],
  'springboot-mybatis': [
    'src/main/java/com/example/',
    'src/main/java/com/example/controller/',
    'src/main/java/com/example/mapper/',
    'src/main/java/com/example/entity/',
    'src/main/resources/mapper/',
    'src/main/resources/application.yml',
    'src/test/java/',
    'pom.xml',
  ],
  'java-multi-module': [
    'parent/',
    'parent/pom.xml',
    'api/',
    'api/pom.xml',
    'api/src/main/java/',
    'core/',
    'core/pom.xml',
    'core/src/main/java/',
    'common/',
    'common/pom.xml',
  ],
  react: [
    'src/',
    'src/main.jsx',
    'src/App.jsx',
    'src/components/',
    'src/pages/',
    'src/hooks/',
    'src/styles/',
    'public/',
    'public/index.html',
    'package.json',
    'vite.config.js',
    '.eslintrc.js',
  ],
  angular: [
    'src/',
    'src/app/',
    'src/app/components/',
    'src/app/services/',
    'src/app/models/',
    'src/assets/',
    'src/environments/',
    'src/index.html',
    'src/main.ts',
    'src/styles.css',
    'angular.json',
    'package.json',
    'tsconfig.json',
  ],
  'quarkus-cqrs-query': [
    'src/main/java/com/example/',
    'src/main/java/com/example/query/',
    'src/main/java/com/example/event/',
    'src/main/java/com/example/handler/',
    'src/main/resources/application.yml',
    'src/test/java/',
    'pom.xml',
  ],
  'quarkus-cqrs-commander': [
    'src/main/java/com/example/',
    'src/main/java/com/example/command/',
    'src/main/java/com/example/handler/',
    'src/main/java/com/example/aggregate/',
    'src/main/resources/application.yml',
    'src/test/java/',
    'pom.xml',
  ],
};
